// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYtBE9CbQIxLKTJXpxO1QGKfiXdxKYgE',
    appId: '1:831267463735:android:9f99e3596429a534d315b2',
    messagingSenderId: '831267463735',
    projectId: 'snapsell-1ca27',
    databaseURL: 'https://snapsell-1ca27-default-rtdb.firebaseio.com',
    storageBucket: 'snapsell-1ca27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHqlW13adQj5g7wgxKAdffey0IhTrWUSw',
    appId: '1:831267463735:ios:3a9f10c6029c932bd315b2',
    messagingSenderId: '831267463735',
    projectId: 'snapsell-1ca27',
    databaseURL: 'https://snapsell-1ca27-default-rtdb.firebaseio.com',
    storageBucket: 'snapsell-1ca27.firebasestorage.app',
    androidClientId: '831267463735-14q41evms5qt2jlu4bpjcua55pllc8u5.apps.googleusercontent.com',
    iosClientId: '831267463735-t7bicke25ldgk8sv6cj85gd4kl2dv2n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.localmarket',
  );
}
